// Regenerates supabase/seed.sql from the sample data: npm run db:seed-file
import { writeFileSync } from "node:fs";
import { MOCK_PROPERTIES, sampleAgentEmail } from "../lib/data/mock-data";

const q = (v: string) => `'${v.replace(/'/g, "''")}'`;
const arr = (vs: string[]) => vs.length ? `array[${vs.map(q).join(", ")}]` : `'{}'::text[]`;

const agents = new Map<string, { id: string; name: string; company: string }>();
for (const p of MOCK_PROPERTIES) {
  const key = `${p.agent.name}|${p.agent.company}`;
  if (!agents.has(key)) {
    agents.set(key, { id: `00000000-0000-4000-9000-${String(agents.size + 1).padStart(12, "0")}`, ...p.agent });
  }
}

const lines = [
  "-- Generated by scripts/generate-seed.ts from lib/data/mock-data.ts. Do not edit by hand.",
  "-- Sample data only: agent emails use the reserved example.com domain.",
  "",
  "insert into public.agents (id, name, company) values",
  [...agents.values()].map(a => `  (${q(a.id)}, ${q(a.name)}, ${q(a.company)})`).join(",\n") + "\non conflict (id) do nothing;",
  "",
  "insert into public.agent_contacts (agent_id, email) values",
  [...agents.values()].map(a => `  (${q(a.id)}, ${q(sampleAgentEmail(a.name))})`).join(",\n") + "\non conflict (agent_id) do nothing;",
  "",
  "insert into public.properties (id, slug, title, area, city, price, type, beds, baths, size_sqm, images, has_tour, verified, description, amenities, agent_id, status, created_at) values",
  MOCK_PROPERTIES.map((p, i) => `  (${[
    q(p.id), q(p.slug), q(p.title), q(p.area), q(p.city), p.price, q(p.type), p.beds, p.baths, p.size,
    arr(p.images), p.tour, p.verified, q(p.description), arr(p.amenities),
    q(agents.get(`${p.agent.name}|${p.agent.company}`)!.id), q("published"),
    // Keep "newest" ordering identical to the sample backend (array order).
    `now() - interval '${i} hours'`
  ].join(", ")})`).join(",\n") + "\non conflict (id) do nothing;",
  ""
];

writeFileSync(new URL("../supabase/seed.sql", import.meta.url), lines.join("\n"));
console.log(`Wrote supabase/seed.sql: ${agents.size} agents, ${MOCK_PROPERTIES.length} properties`);
